<?php
namespace Enums;

enum Handshake: int{
  case HELLO_REQUEST_RESERVED = 0;
  case CLIENT_HELLO = 1;
  case SERVER_HELLO = 2;
  case NEW_SESSION_TICKET = 4;
  case END_OF_EARLY_DATA = 5;
  case ENCRYPTED_EXTENSIONS = 8;
  case REQUEST_CONNECTION_ID = 9;
  case NEW_CONNECTION_ID = 10;
  case CERTIFICATE = 11;
  case SERVER_KEY_EXCHANGE_RESERVED = 12;
  case CERTIFICATE_REQUEST = 13;
  case SERVER_HELLO_DONE_RESERVED = 14;
  case CERTIFICATE_VERIFY = 15;
  case CLIENT_KEY_EXCHANGE_RESERVED = 16;
  case CLIENT_CERTIFICATE_REQUEST = 17;
  case FINISHED = 20;
  case CERTIFICATE_URL_RESERVED = 21;
  case CERTIFICATE_STATUS_RESERVED = 22;
  case SUPPLEMENTAL_DATA_RESERVED = 23;
  case KEY_UPDATE = 24;
  case COMPRESSED_CERTIFICATE = 25;
  case EKT_KEY = 26;
  case MESSAGE_HASH = 254;
}
